from django.urls import path, re_path
from django.views.generic import RedirectView

from . import views, owner, sync


urlpatterns = [
    path('robots.txt', views.public_file, {'name': 'robots.txt', 'content_type': 'text/plain; charset=utf-8'}),
    path('sitemap.xml', views.public_file, {'name': 'sitemap.xml', 'content_type': 'application/xml; charset=utf-8'}),
    path('api/desktop/sync', sync.sync_api),
    path('api/owner/members', owner.members),
    path('api/owner/members/<str:source>/<int:member_id>', owner.member),
    path('api/owner/activity', owner.activity),
    path('api/owner/overview', owner.overview),
    path('api/owner/plans', owner.plans),
    path('api/owner/plans/<int:plan_id>', owner.plans),
    path('owner.js', views.public_file, {'name': 'owner.js'}),
    path('owner.css', views.public_file, {'name': 'owner.css'}),
    path("", views.page, {"name": "index.html"}),
    path("coaches", views.page, {"name": "coaches.html"}),
    path("bodybuilding", views.page, {"name": "bodybuilding.html"}),
    path("calisthenics", views.page, {"name": "calisthenics.html"}),
    path("functional", views.page, {"name": "functional.html"}),
    path("login", views.page, {"name": "login.html"}),
    path("signup", views.page, {"name": "signup.html"}),
    path("pending", views.page, {"name": "pending.html"}),
    path("dashboard", views.page, {"name": "dashboard.html"}),
    path("admin", views.page, {"name": "admin.html"}),
    path("coach-panel", views.page, {"name": "coach-panel.html"}),
    path("index.html", RedirectView.as_view(url='/', permanent=True, query_string=True)),
    path("coaches.html", RedirectView.as_view(url='/coaches', permanent=True, query_string=True)),
    path("bodybuilding.html", RedirectView.as_view(url='/bodybuilding', permanent=True, query_string=True)),
    path("calisthenics.html", RedirectView.as_view(url='/calisthenics', permanent=True, query_string=True)),
    path("functional.html", RedirectView.as_view(url='/functional', permanent=True, query_string=True)),
    path("login.html", RedirectView.as_view(url='/login', permanent=True, query_string=True)),
    path("signup.html", RedirectView.as_view(url='/signup', permanent=True, query_string=True)),
    path("pending.html", RedirectView.as_view(url='/pending', permanent=True, query_string=True)),
    path("dashboard.html", RedirectView.as_view(url='/dashboard', permanent=True, query_string=True)),
    path("admin.html", RedirectView.as_view(url='/admin', permanent=True, query_string=True)),
    path("coach-panel.html", RedirectView.as_view(url='/coach-panel', permanent=True, query_string=True)),
    path("styles.css", views.public_file, {"name": "styles.css"}),
    path("app.js", views.public_file, {"name": "app.js"}),
    re_path(r"^assets/(?P<name>.+)$", views.asset_file),
    path("api/health", views.health),
    path("api/plans", views.plans_api),
    path("api/signup/otp/send", views.signup_otp_send_api),
    path("api/signup", views.signup_api),
    path("api/login", views.login_api),
    path("api/logout", views.logout_api),
    path("api/me", views.me_api),
    path("api/admin/users", views.admin_users_api),
    path("api/admin/users/<int:user_id>/status", views.admin_user_status_api),
    path("api/coach/profile", views.coach_profile_api),
    path("api/coach/members", views.coach_members_api),
    path("api/coach/programs", views.coach_programs_api),
    path("api/coach/programs/<int:program_id>", views.coach_program_api),
    path("api/member/program", views.member_program_api),
    path("api/desktop/coaches", views.desktop_coaches_api),
    path("api/desktop/coaches/<int:coach_id>", views.desktop_coach_api),
    path("api/desktop/plans", views.desktop_plans_api),
    path("api/desktop/plans/<int:plan_id>", views.desktop_plan_api),
    path("api/desktop/members/<int:legacy_member_id>/password", views.desktop_member_password_api),
    path("api/desktop/applications", views.desktop_applications_api),
    path("api/desktop/applications/<int:application_id>/activate", views.desktop_activate_api),
]
