# Generated by Django 5.2.17 on 2026-08-10 21:40

import django.db.models.deletion
import django.utils.timezone
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('father_name', models.TextField(blank=True, null=True)),
                ('national_id', models.TextField(blank=True, null=True)),
                ('certificate_no', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.TextField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.TextField()),
                ('plan', models.TextField()),
                ('embedding', models.TextField(blank=True, null=True)),
                ('face_image', models.BinaryField(blank=True, null=True)),
                ('used_sessions', models.IntegerField(default=0)),
                ('signup_time', models.TextField()),
                ('debt', models.IntegerField(default=0)),
                ('payment', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('gender', models.CharField(choices=[('all', 'همه'), ('male', 'مرد'), ('female', 'زن')], default='all', max_length=8)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('sessions_per_month', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(db_index=True, max_length=11, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('address', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('member', 'عضو'), ('coach', 'مربی'), ('staff', 'پذیرش'), ('admin', 'مدیر')], default='member', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'در انتظار مراجعه'), ('active', 'فعال'), ('suspended', 'تعلیق\u200cشده')], db_index=True, default='pending', max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', members.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار مراجعه'), ('active', 'فعال'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده')], db_index=True, default='pending', max_length=12)),
                ('legacy_member_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.PositiveBigIntegerField(default=0)),
                ('face_registered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_application', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='members.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'requested_at'], name='idx_application_status_date')],
            },
        ),
    ]
