# Generated by Django 5.2.17 on 2026-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_loginevent_owneraudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSyncCursor',
            fields=[
                ('source', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('digest', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('local_id', models.PositiveBigIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'local_id'), name='unique_gym_sync_record')],
            },
        ),
    ]
