# Generated by Django 5.2.17 on 2026-10-04 20:51

from django.db import migrations, models


def preserve_existing_owners(apps, schema_editor):
    User = apps.get_model('members', 'User')
    User.objects.using(schema_editor.connection.alias).filter(is_superuser=True).update(role='owner')


def reverse_owner_roles(apps, schema_editor):
    User = apps.get_model('members', 'User')
    User.objects.using(schema_editor.connection.alias).filter(role='owner').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_gymremotecommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'عضو'), ('coach', 'مربی'), ('staff', 'پذیرش'), ('admin', 'ادمین'), ('owner', 'مالک')], default='member', max_length=12),
        ),
        migrations.RunPython(preserve_existing_owners, reverse_owner_roles),
    ]
