# Generated by Django 5.2.17 on 2026-10-07 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_owner_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='coach_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='main_goal',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField(default=django.utils.timezone.localdate)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('body_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('arms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('thighs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bench_press', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('squat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deadlift', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pull_ups', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fitness_notes', models.TextField(blank=True)),
                ('mobility_notes', models.TextField(blank=True)),
                ('strength_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assessments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('muscle_group', models.CharField(max_length=24)),
                ('equipment', models.CharField(blank=True, max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('common_mistakes', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['muscle_group', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='members.workoutprogram')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(blank=True, max_length=180)),
                ('training_day', models.CharField(blank=True, max_length=160)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('group_label', models.CharField(blank=True, max_length=160)),
                ('exercises', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی\u200cشده'), ('in_progress', 'در حال تمرین'), ('completed', 'انجام\u200cشده'), ('cancelled', 'لغوشده'), ('no_show', 'عدم حضور')], default='scheduled', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coached_sessions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.workoutprogram')),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoachNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reported_pain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_coach_notes', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_notes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.trainingsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_goal', models.CharField(blank=True, max_length=40)),
                ('experience', models.CharField(blank=True, max_length=40)),
                ('frequency', models.PositiveSmallIntegerField(default=3)),
                ('preferred_style', models.CharField(blank=True, max_length=160)),
                ('limitations', models.TextField(blank=True)),
                ('injuries', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('reported_pain', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_training_profiles', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coach', 'member'), name='unique_coach_training_profile')],
            },
        ),
    ]
