# Generated by Django 5.2.17 on 2026-10-07 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_exercise_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('read_notifications', models.JSONField(default=list)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('closed', 'بسته\u200cشده')], default='pending', max_length=12)),
                ('reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(max_length=180)),
                ('training_day', models.CharField(max_length=160)),
                ('day_index', models.PositiveSmallIntegerField(default=0)),
                ('exercises', models.JSONField(default=list)),
                ('personal_note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_workout_logs', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.workoutprogram')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('member',), name='one_open_member_workout')],
            },
        ),
    ]
