# Generated by Django 5.2.17 on 2026-10-10 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('code_digest', models.CharField(blank=True, max_length=64)),
                ('token_digest', models.CharField(blank=True, max_length=64)),
                ('password_digest', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField()),
                ('window_started_at', models.DateTimeField()),
                ('send_count', models.PositiveSmallIntegerField(default=0)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
